# Generated by Django 4.2 on 2023-04-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_app', '0002_alter_adaccount_ad_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionitem',
            name='value',
            field=models.FloatField(default=0, max_length=255),
        ),
    ]
