# Generated by Django 4.2 on 2023-04-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_app', '0004_alter_conditionitem_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='value',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='filter',
            name='operator_choice',
            field=models.CharField(choices=[('D', 'Choose Operator'), ('A', 'All'), ('O', 'At Least One')], default='A', max_length=1),
        ),
    ]
