# Generated by Django 4.2 on 2023-04-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_app', '0005_alter_action_value_alter_filter_operator_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaccount',
            name='ad_account_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
